version: "3.1"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    user: '0:0'
    container_name: sql-server-db
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Oma.2017
      MSSQL_PID: Express
    volumes:
      - ~/docker/sqlserver-data:/var/opt/mssql/data
